### ISSUE TITLE
Enlever les champs spécifiques à recolnat 

### ISSUE THREAD

**Issue by webmastard** [e-ReColNat/recolnat-diff#2]
Enlever dans les classes de type DiffEntity les champs spécifiques à Recolnat

**Comment by webmastard** [comment]
champs exclus de la recherche de diffs : 
biblio : sourcefileid
determination : 'hascoordinates', 'verbatimcountry', 'sourcefileid', 'averagealtituderounded'
localisation : sourcefileid
multimedia : 'created', 'modified', 'discriminator'
recolte : 'eventdate', 'sourcefileid'
specimen : 'created', 'modified', 'dwcaid', 'hasmedia', 'sourcefileid', 'hascoordinates'
stratigraphy : sourcefileid
taxon : 'created', 'modified', 'sourcefileid', 'dwcataxonid' 

@jhusson : tu peux me dire si j'en oublie et si j'en met en trop

**Comment by jhusson** [comment]
@webmastard 'verbatimcountry' ne fait pas parti de determination, ni 'averagealtituderounded' mais de recolte.

verbatimcountry doit être inclus, il représente la localité originale issue de l'étiquette.

**Comment by webmastard** [comment]
@jhusson tu as l'oeil !
